name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: Compile resume pdf
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: thomasweise/docker-texlive-full:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd data
            pdflatex srivilliamsai.tex
            mv srivilliamsai.pdf srivilliamsai_resume.pdf
      
      - name: Convert PDF to PNG preview
        run: |
          sudo apt-get update && sudo apt-get install -y poppler-utils imagemagick
          pdftoppm srivilliamsai_resume.pdf resume_preview -png -singlefile -rx 150 -ry 150
          mv resume_preview.png resume_preview.png || true
            
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update resume PDF and preview [skip ci]"
          file_pattern: "*.pdf *.png"